rails1/lojadecamisetas/config/routes.rb
Rails.application.routes.draw do
	
	resources :departamentos

	get "/produtos/busca" => "produtos#busca", as: :busca_produto
	resources :produtos, only: [:new, :create, :destroy, :edit, :update]

    root "produtos#index"

end

rails1/lojadecamisetas/app/models/departamento.rb
class Departamento < ActiveRecord::Base
end

rails1/lojadecamisetas/app/models/produto.rb
class Produto < ActiveRecord::Base

	belongs_to :departamento  
	
	validates :quantidade, presence: true
	validates :nome, length: { minimum: 5 }

end

rails1/lojadecamisetas/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rails1/lojadecamisetas/app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :set_departamento, only: [:show, :edit, :update, :destroy]

  # GET /departamentos
  # GET /departamentos.json
  def index
    @departamentos = Departamento.all
  end

  # GET /departamentos/1
  # GET /departamentos/1.json
  def show
  end

  # GET /departamentos/new
  def new
    @departamento = Departamento.new
  end

  # GET /departamentos/1/edit
  def edit
  end

  # POST /departamentos
  # POST /departamentos.json
  def create
    @departamento = Departamento.new(departamento_params)

    respond_to do |format|
      if @departamento.save
        format.html { redirect_to @departamento, notice: 'Departamento was successfully created.' }
        format.json { render :show, status: :created, location: @departamento }
      else
        format.html { render :new }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departamentos/1
  # PATCH/PUT /departamentos/1.json
  def update
    respond_to do |format|
      if @departamento.update(departamento_params)
        format.html { redirect_to @departamento, notice: 'Departamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @departamento }
      else
        format.html { render :edit }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departamentos/1
  # DELETE /departamentos/1.json
  def destroy
    @departamento.destroy
    respond_to do |format|
      format.html { redirect_to departamentos_url, notice: 'Departamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departamento
      @departamento = Departamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def departamento_params
      params.require(:departamento).permit(:nome)
    end
end

rails1/lojadecamisetas/app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController

	before_action :set_produto, only: [:edit, :update, :destroy]

	def index
        @produtos_por_nome = Produto.order(:nome)
        @produtos_por_preco = Produto.order(:preco)
    end

    def new
	    @produto = Produto.new
	    renderiza_new
	end

	def create
	    valores = produto_params
	    @produto = Produto.new valores
	    if @produto.save
	    	flash[:notice] = "Produto salvo com sucesso"
	        redirect_to root_url
	    else
	        render :new
	    end
	end

	def edit
	   @departamentos = Departamento.all
	   render :edit
	end

	def update
	    valores = produto_params
	    if @produto.update valores
	        flash[:notice] = "Produto atualizado com sucesso"
	        redirect_to root_url
	    else
	        renderiza_new
	    end
	end

	def destroy
	    @produto.destroy
	    redirect_to root_url
	end

	def busca
		@nome_a_buscar = params[:nome]
    	@produtos = Produto.where "nome like ?", "%#{@nome_a_buscar}%"
	end

	private

	def renderiza_new
	    @departamentos = Departamento.all
	    render :new
	end

	def set_produto
	    id = params[:id]
	    @produto = Produto.find(id)
	end

	def produto_params
	    params.require(:produto).permit :nome, :preco, :descricao, :quantidade, :departamento_id
	end

end

rails1/lojadecamisetas/app/helpers/application_helper.rb
module ApplicationHelper
end

rails1/lojadecamisetas/app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

rails1/lojadecamisetas/app/helpers/produtos_helper.rb
module ProdutosHelper
end

rails1/lojadecamisetas/app/views/departamentos/_form.html.erb
<%= form_for(@departamento) do |f| %>
  <% if @departamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@departamento.errors.count, "error") %> prohibited this departamento from being saved:</h2>

      <ul>
      <% @departamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails1/lojadecamisetas/app/views/departamentos/edit.html.erb
<h1>Editing Departamento</h1>

<%= render 'form' %>

<%= link_to 'Show', @departamento %> |
<%= link_to 'Back', departamentos_path %>

rails1/lojadecamisetas/app/views/departamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Departamentos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departamentos.each do |departamento| %>
      <tr>
        <td><%= departamento.nome %></td>
        <td><%= link_to 'Show', departamento %></td>
        <td><%= link_to 'Edit', edit_departamento_path(departamento) %></td>
        <td><%= link_to 'Destroy', departamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Departamento', new_departamento_path %>

rails1/lojadecamisetas/app/views/departamentos/new.html.erb
<h1>New Departamento</h1>

<%= render 'form' %>

<%= link_to 'Back', departamentos_path %>

rails1/lojadecamisetas/app/views/departamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @departamento.nome %>
</p>

<%= link_to 'Edit', edit_departamento_path(@departamento) %> |
<%= link_to 'Back', departamentos_path %>

rails1/lojadecamisetas/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lojadecamisetas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= nav_bar brand: "Kunstee", brand_link: root_url do %>
    <%= form_tag busca_produto_path, method: :get, class: "navbar-form navbar-right" do %>
        <div class="form-group">
            <%= text_field_tag :nome, @nome_a_buscar, class: "form-control" %>
            <%= button_to "Buscar", nil, class: "btn btn-default" %>
        </div>
    <% end %>
<% end %>

<div class="container">
    <%= yield %>
</div>

</body>
</html>

rails1/lojadecamisetas/app/views/produtos/_form.html.erb
<%= form_for @produto do |f| %>

    <% @produto.errors.full_messages.each do |message|%>
        <div class="alert alert-danger" role="alert"><%=message%></div>
    <% end %>

    <div class="form-group">
        <%= f.label :nome %>
        <%= f.text_field :nome, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :descricao %>
        <%= f.text_area :descricao, class: "form-control", rows: 4 %>
    </div>

    <div class="form-group">
        <%= f.label :departamento %>
        <%= f.collection_select :departamento_id, @departamentos, :id, :nome, {}, class: "form-control" %>
    </div>

    <div class="form-inline">
        <div class="form-group">
            <%= f.label :quantidade %>
            <%= f.number_field :quantidade, step: 1, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :preco %>
            <%= f.number_field :preco, class: "form-control" %>
        </div>

        <%= f.submit texto_da_acao, class: "btn btn-primary" %>

    </div>

<% end %>

rails1/lojadecamisetas/app/views/produtos/_produto.html.erb
<tr>
    <td><%= produto.nome %></td>
    <td><%= produto.descricao %></td>
    <td><%= produto.preco %></td>
    <td><%= button_to "Remover", produto, method: :delete, class: "btn btn-danger", data: { confirm: "Tem certeza que deseja remover #{produto.nome}?" } %></td>
    <td><%= link_to "Alterar", edit_produto_path(produto), class: "btn btn-default" %></td>
</tr>

rails1/lojadecamisetas/app/views/produtos/busca.html.erb
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Preço</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <%= render partial: "produto", collection: @produtos %>
    </tbody>
</table>

rails1/lojadecamisetas/app/views/produtos/edit.html.erb
<%= render partial: 'form', locals: { texto_da_acao: 'Atualizar o produto'} %>

rails1/lojadecamisetas/app/views/produtos/index.html.erb
<div class="container">
<% if flash[:notice] %>
    <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
<% end %>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Preço</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <%= render partial: "produto", collection: @produtos_por_nome %>
    </tbody>    
</table>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Preço</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <%= render partial: "produto", collection: @produtos_por_preco %>
    </tbody>    
</table>

<%= link_to "Criar novo produto", new_produto_path %>

</div>

rails1/lojadecamisetas/app/views/produtos/new.html.erb
<%= render partial: 'form', locals: { texto_da_acao: 'Criar o produto'} %>